INSERT INTO products 
(name, description, price, stock, image, category) 
VALUES
('OnePlus Nord CE', 'Smartphone OnePlus dengan performa tinggi dan desain minimalis.', 3999000, 17, 'product.jpg', 'Gadget'),
('ASUS ROG Phone', 'Smartphone gaming ASUS dengan performa tinggi dan sistem pendingin khusus.', 10999000, 8, 'product.jpg', 'Gadget'),
('Wireless Earbuds TWS', 'Earbuds wireless dengan fitur noise cancellation.', 499000, 40, 'product.jpg', 'Gadget'),
('Smartwatch Active', 'Jam tangan pintar dengan monitor aktivitas dan kesehatan.', 899000, 30, 'product.jpg', 'Gadget'),
('Power Bank 20000mAh', 'Power bank berkapasitas besar dengan fast charging.', 399000, 35, 'product.jpg', 'Gadget'),
('Mechanical Keyboard RGB', 'Keyboard mechanical dengan lampu RGB.', 799000, 20, 'product.jpg', 'Gaming'),
('Gaming Mouse Pro', 'Mouse gaming dengan sensor presisi tinggi.', 549000, 28, 'product.jpg', 'Gaming'),
('Gaming Headset 7.1', 'Headset gaming surround sound 7.1 dengan microphone.', 699000, 18, 'product.jpg', 'Gaming'),
('Gaming Mousepad XL', 'Mousepad ukuran XL dengan permukaan gaming.', 199000, 50, 'product.jpg', 'Gaming'),
('Game Controller Wireless', 'Controller wireless kompatibel dengan PC dan console.', 599000, 22, 'product.jpg', 'Gaming'),

('Basic T-Shirt Black', 'Kaos katun basic berwarna hitam.', 99000, 60, 'product.jpg', 'Fashion'),
('Basic T-Shirt White', 'Kaos katun basic berwarna putih.', 99000, 55, 'product.jpg', 'Fashion'),
('Hoodie Oversize', 'Hoodie oversize berbahan cotton fleece.', 299000, 30, 'product.jpg', 'Fashion'),
('Denim Jacket', 'Jaket denim casual untuk penggunaan sehari-hari.', 449000, 20, 'product.jpg', 'Fashion'),
('Cargo Pants', 'Celana cargo dengan banyak kantong.', 329000, 25, 'product.jpg', 'Fashion'),
('Running Shoes', 'Sepatu olahraga ringan untuk aktivitas running.', 599000, 32, 'product.jpg', 'Fashion'),
('Canvas Sneakers', 'Sneakers casual berbahan canvas.', 349000, 27, 'product.jpg', 'Fashion'),
('Baseball Cap', 'Topi baseball casual dengan desain minimalis.', 129000, 45, 'product.jpg', 'Fashion'),

('Electric Kettle', 'Ketel listrik dengan kapasitas 1.8 liter.', 249000, 35, '.product.jpg', 'Home Tools'),
('Air Fryer 4L', 'Air fryer digital dengan kapasitas 4 liter.', 899000, 18, 'product.jpg', 'Home Tools'),
('Vacuum Cleaner Mini', 'Vacuum cleaner portable untuk membersihkan rumah.', 399000, 25, 'product.jpg', 'Home Tools'),
('Table Lamp LED', 'Lampu meja LED dengan tingkat kecerahan yang dapat diatur.', 159000, 40, 'product.jpg', 'Home Tools'),
('Digital Kitchen Scale', 'Timbangan dapur digital dengan kapasitas 10kg.', 119000, 35, 'product.jpg', 'Home Tools'),
('Portable Blender', 'Blender portable rechargeable untuk membuat minuman.', 279000, 22, 'product.jpg', 'Home Tools'),
('Non-Stick Frying Pan', 'Wajan anti lengket untuk memasak sehari-hari.', 229000, 30, 'product.jpg', 'Home Tools'),
('Storage Box', 'Kotak penyimpanan plastik dengan tutup.', 89000, 70, 'product.jpg', 'Home Tools'),

('USB-C Cable', 'Kabel USB-C fast charging dengan panjang 1 meter.', 79000, 80, 'product.jpg', 'Aksesoris'),
('Phone Stand', 'Stand smartphone adjustable untuk meja kerja.', 99000, 45, 'product.jpg', 'Aksesoris'),
('Laptop Sleeve 14 Inch', 'Sleeve laptop dengan bahan tahan air.', 179000, 30, 'product.jpg', 'Aksesoris'),
('Wireless Charger', 'Charger wireless dengan desain minimalis.', 199000, 35, 'product.jpg', 'Aksesoris'),
('Webcam Cover', 'Penutup kamera laptop untuk menjaga privasi.', 39000, 100, 'product.jpg', 'Aksesoris'),
('HDMI Cable', 'Kabel HDMI high speed untuk monitor dan TV.', 89000, 65, 'product.jpg', 'Aksesoris'),
('Bluetooth Speaker', 'Speaker Bluetooth portable dengan suara stereo.', 299000, 25, 'product.jpg', 'Aksesoris'),

('Clean Code', 'Buku panduan menulis kode yang bersih dan mudah dipelihara.', 250000, 15, 'product.jpg', 'Books'),
('The Pragmatic Programmer', 'Buku tentang praktik pemrograman profesional.', 280000, 12, 'product.jpg', 'Books'),
('Zero to One', 'Buku bisnis dan startup karya Peter Thiel.', 150000, 20, 'product.jpg', 'Books'),
('Atomic Habits', 'Buku tentang membangun kebiasaan positif.', 135000, 25, 'product.jpg', 'Books'),
('The Psychology of Money', 'Buku tentang psikologi dan perilaku dalam mengelola uang.', 145000, 18, 'product.jpg', 'Books'),

('Yoga Mat', 'Matras yoga anti-slip untuk latihan di rumah.', 199000, 30, 'product.jpg', 'Sports'),
('Dumbbell 5kg', 'Dumbbell besi untuk latihan kekuatan.', 249000, 25, 'product.jpg', 'Sports'),
('Resistance Band Set', 'Set resistance band dengan berbagai tingkat resistensi.', 159000, 35, 'product.jpg', 'Sports'),
('Skipping Rope', 'Tali skipping dengan handle ergonomis.', 79000, 50, 'product.jpg', 'Sports'),
('Football', 'Bola sepak standar untuk latihan dan pertandingan.', 179000, 28, 'product.jpg', 'Sports'),

('Office Chair', 'Kursi kantor ergonomis dengan sandaran punggung.', 1299000, 12, 'product.jpg', 'Furniture'),
('Study Desk', 'Meja belajar minimalis dengan ruang penyimpanan.', 899000, 10, 'product.jpg', 'Furniture'),
('Bookshelf', 'Rak buku kayu dengan desain minimalis.', 699000, 14, 'product.jpg', 'Furniture'),
('LED Monitor 24 Inch', 'Monitor Full HD 24 inch untuk pekerjaan dan hiburan.', 1599000, 16, 'product.jpg', 'Computer'),
('Mechanical Keyboard Wireless', 'Keyboard mechanical wireless dengan koneksi Bluetooth.', 899000, 20, 'product.jpg', 'Computer'),
('USB Hub 4 Port', 'USB hub dengan empat port tambahan.', 149000, 45, 'product.jpg', 'Computer'),
('Laptop Cooling Pad', 'Cooling pad laptop dengan kipas pendingin.', 219000, 32, 'product.jpg', 'Computer'),
('External SSD 1TB', 'SSD eksternal 1TB dengan koneksi USB-C.', 1199000, 18, 'product.jpg', 'Computer');